<?php

// VERY IMPORTANT:
// NOTE: NORMALLY I WOULD USE THIS VALIDATOR CLASS TO VALIDATE FORMS ETC AND WITH THIS IS CLASS IT CAN BE USED ANYWHERE IN THE APP
// BUT TRYING TO VALIDATE THE SWITCH STATEMENT WHEN ITS CALLED, WAS A PAIN AND I JUST COULDNT GET IT WORKING PROPERLY
// THIS IS WHY YOU WILL SEE A UNDEFINED ARRAY KEY FOR WHEN YOU SUBMIT THE FORM
// THATS WHY IS MODIFIED THE FRONTEND HTML INPUTS TO GIVE VALIDATION.
// VALIDATING THE SKU, NAME, PRICE, TYPE. CAN BE EASILY DONE WITH THIS CLASS, But the rest I just dont know

class Validator {
    
    
    
}